{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(endpoint_requests_total{endpoint=\"all\"}[1m])",
     "legendFormat": "requested latency"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(purchase_count_successful_total{type=\"successful\"}[1m])",
     "legendFormat": "pizza purchase"
    },
    {
     "expr": "rate(purchase_count_failed_total{type=\"failed\"}[1m])",
     "legendFormat": "purchase failure"
    },
    {
     "expr": "rate(purchase_cost_total{type=\"cost\"}[1m])",
     "legendFormat": "Revenue/minute"
    },
    {}
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_methods_total{method=\"GET\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(http_methods_total{method=\"DELETE\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(http_methods_total{method=\"POST\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(http_methods_total{method=\"PUT\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(http_requests_total{type=\"all\"}[1m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "user_active_count_total{type=\"active_users\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage_total{type=\"system\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "system_memory_usage_total{type=\"system\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(auth_successful_total{type=\"authentication\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_failed_total{type=\"authentication\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  }
 ]
}